name: Bloquear Pre Release hasta las 8 PM en Chile

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    if: ${{ startsWith(github.event.pull_request.title, 'Pre release 2023') }}
    runs-on: ubuntu-latest
    steps:
    - name: Esperar hasta hora definida
      run: |
          echo "PR bloqueado hasta las 8pm CL"
          current_epoch=$(TZ=America/Santiago date +%s)
          target_epoch=$(TZ=America/Santiago date -d "11:48:00" +%s)
          sleep_seconds=$(( $target_epoch - $current_epoch ))
          if [ $sleep_seconds > 0 ]; then
            sleep $sleep_seconds
          fi
         
    - name: Desbloquear PR
      run: |
        echo "PR desbloqueado"
       
