name: Bloquear Pre Release hasta las 8 PM en Chile

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bloquear-pre-release-hasta-las-8pm:
    if: ${{ startsWith(github.event.pull_request.title, 'Prerelease a production') }}
    runs-on: ubuntu-latest
    steps:
    - name: Esperar hasta hora definida
      run: |
          pr_title="${{ github.event.pull_request.title }}"
          deploy_date=$(echo "$pr_title" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}')
          current_epoch=$(TZ=America/Santiago date +%s)
          target_epoch=$(TZ=America/Santiago date -d "$deploy_date 20:00:00" +%s)
          sleep_seconds=$(( $target_epoch - $current_epoch ))
          if [ $sleep_seconds -gt 0 ]; then
            echo "Todavia no es la hora de deployar, espera hasta las 8pm de Chile"
            exit 1
          fi
